#include "stm32f1xx_hal.h"
#ifndef	__74HC595__H
#define __74HC595__H
#endif  

#define SPI_MOSI_0  		 HAL_GPIO_WritePin(GPIOA, GPIO_PIN_7,GPIO_PIN_RESET)
#define SPI_MOSI_1  		 HAL_GPIO_WritePin(GPIOA, GPIO_PIN_7,GPIO_PIN_SET)

#define SPI_CLK_0   		 HAL_GPIO_WritePin(GPIOA, GPIO_PIN_5,GPIO_PIN_RESET)
#define SPI_CLK_1  			 HAL_GPIO_WritePin(GPIOA, GPIO_PIN_5,GPIO_PIN_SET)

#define SPI_NSS_LCD_0 	 HAL_GPIO_WritePin(GPIOA, GPIO_PIN_0,GPIO_PIN_RESET)
#define SPI_NSS_LCD_1  	 HAL_GPIO_WritePin(GPIOA, GPIO_PIN_0,GPIO_PIN_SET)

#define SPI_NSS_JOY1_0   HAL_GPIO_WritePin(GPIOB, GPIO_PIN_5,GPIO_PIN_RESET)
#define SPI_NSS_JOY1_1   HAL_GPIO_WritePin(GPIOB, GPIO_PIN_5,GPIO_PIN_SET)

#define SPI_NSS_JOY2_0   HAL_GPIO_WritePin(GPIOA, GPIO_PIN_2,GPIO_PIN_RESET)
#define SPI_NSS_JOY2_1   HAL_GPIO_WritePin(GPIOA, GPIO_PIN_2,GPIO_PIN_SET)

void HC595Send_Data(uint8_t date);

